module_order:
  - fastqc:
      name: "R1 FastQC (raw reads)"
      anchor: "R1_fastqc_raw"
      info: "This section of the report shows FastQC results for R1 before adapter trimming."
      path_filters:
        - "results/qc/raw/*.1_fastqc.zip"
  - fastqc:
      name: "R2 FastQC (raw reads)"
      anchor: "R2_fastqc_raw"
      info: "This section of the report shows FastQC results for R2 before adaptertrimming."
      path_filters:
        - "results/qc/raw/*.2_fastqc.zip"
  - fastqc:
      name: "R1 FastQC (trimmed reads)"
      anchor: "R1_fastqc_trimmed"
      info: "This section of the report shows FastQC results for R1 after adapter trimming."
      path_filters:
        - "results/qc/trimmed/*/*.1_fastqc.zip"
  - fastqc:
      name: "R2 FastQC (trimmed reads)"
      anchor: "R2_fastqc_trimmed"
      info: "This section of the report shows FastQC results for R2 after adapter trimming."
      path_filters:
        - "results/qc/trimmed/*/*.2_fastqc.zip"
  - fastp
  - salmon
#  - salmon:
#      name: "Salmon Quant"
#      anchor: "salmon_quant"
#      info: "This section of the report shows Salmon Quant results using trimmed reads."
#      path_filters:
#        - "results/mapping/*/*/*.salmon"

extra_fn_clean_exts:
  - ".1"
  - ".2"
  - "_fastp"
  - ".salmon"

table_columns_visible:
  R1_fastqc_raw:
    percent_duplicates: True
    percent_gc: True
    avg_sequence_length: False
    median_sequence_length: False
    percent_fails: False
    total_sequences: True
  R2_fastqc_raw:
    percent_duplicates: True
    percent_gc: True
    avg_sequence_length: False
    median_sequence_length: False
    percent_fails: False
    total_sequences: True
  R1_fastqc_trimmed:
    percent_duplicates: True
    percent_gc: True
    avg_sequence_length: False
    median_sequence_length: False
    percent_fails: False
    total_sequences: True
  R2_fastqc_trimmed:
    percent_duplicates: True
    percent_gc: True
    avg_sequence_length: False
    median_sequence_length: False
    percent_fails: False
    total_sequences: True
  fastp:
    pct_duplication: True
    after_filtering_q30_rate: False
    after_filtering_q30_bases: False
    filtering_result_passed_filter_reads: True
    after_filtering_gc_content: True
    pct_surviving: True
    pct_adapter: True
  salmon: True
