################################
#### Config for Salmon Quant
################################

# Name of project
project_name: 'species1'

# Path to sample manifest
samples: 'config/samples.tsv'

# Path to CDS (or CDS+decoys) to use for quant
# reference name : absolute path (can be gzipped)
ref_path:
  'genome2': 'path/to/genome2.fa.gz'

# To add decoys, uncomment the following commands and provided the path to the decoy sequence names file.
#ref_Salmon_index:
#  params: '--decoys /path/to/seq/names/file.txt'

